[package]
name = "coll-tx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cops = { version = "0.1.0", path = "../../crates/cops"}
sha2 = "0.10.8"
rand ="0.8.5"
tokio = "1.37.0"