[package]
name = "vlc-dag"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html



[dependencies]
vlc = { version = "0.1.0", path = "../../crates/vlc" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = [
    "net",
    "rt-multi-thread",
    "macros",
    "time",
] }
rand = { version = "0.8" }
lmdb-rs = "0.7.6"